all:
  children:
    nginx:
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519-skokado.pem
      hosts:
        nginx-server-1:
          ansible_host: 52.197.201.116
